Change to only release manually

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,19 +1,31 @@
-name: goreleaser
+name: release
 
 on:
-  release:
-    # Only run when a release is created, but not when it has been published.
-    #
-    # Release process:
-    # 1. you create a draft release
-    # 2. this "release.yml" workflow gets triggered
-    # 3. goreleaser builds binaries and pushes them as release artifacts
-    # 4. goreleaser publishes the release (on GitHub, Homebrew, Docker, etc.)
-    #
-    # This allows us to have build errors on step 3. without us having to
-    # roll back a release or artificially bump the version just because of
-    # a CI/CD issue.
-    types: [created]
+  # Only run when triggered manually.
+  #
+  # Release process:
+  # 1. you create a draft release
+  # 2. you may edit the draft how many times you want, no automation has kicked in yet
+  # 3. you manually trigger this workflow
+  # 4. this workflow builds and publishes the release (unmarks it as draft)
+  #
+  # This allows us to have build errors on step 3. without us having to
+  # roll back a release or artificially bump the version just because of
+  # a CI/CD issue.
+  workflow_dispatch:
+    inputs:
+      tag-name:
+        description: GitHub release tag name of the draft release you want to publish.
+        required: true
+        type: string
+      environment:
+        description: GitHub Action environment to publish to.
+        default: production
+        type: environment
+      dry-run:
+        description: When enabled, will only build and upload the assets to the release, but won't publish it
+        type: boolean
+        default: false
 
 permissions:
   # Required to upload binaries to GitHub releases
@@ -26,9 +38,16 @@ permissions:
   id-token: write
 
 jobs:
-  goreleaser:
+  build:
     runs-on: ubuntu-latest
     steps:
+      - name: Validate tag name format
+        run: |
+          if [[ ! "${{ inputs.tag-name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-z0-9.\-]+)?$ ]]; then
+            echo "Invalid tag name format. Must be in the form v1.2.3 or v1.2.3-foobar.1"
+            exit 1
+          fi
+
       - name: Checkout
         uses: actions/checkout@v4
         with:
@@ -36,6 +55,11 @@ jobs:
 
       - name: Fetch tags
         run: git fetch --force --tags
+
+      - name: Create temp tag
+        env:
+          TAG_NAME: ${{ inputs.tag-name }}
+        run: git tag "$TAG_NAME" -m "$TAG_NAME"
 
       - name: Set up Go
         uses: actions/setup-go@v5
@@ -46,7 +70,10 @@ jobs:
         uses: goreleaser/goreleaser-action@v6
         with:
           version: "~> v2"
-          args: release --clean
+          # Using `--skip=publish` as we need some further processing
+          # like creating deb/rpm repos & attestations, which are done
+          # in later steps
+          args: release --clean --skip=publish
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GLOBAL_GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
@@ -65,40 +92,10 @@ jobs:
             dist/*.deb
             dist/metadata.json
 
-  homebrew:
-    name: Bump Homebrew formula
-    # Skip this job in case of git pushes to prerelease tags
-    if: "!contains(github.ref, '-')"
+  release:
+    needs: build
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-    needs: goreleaser
-    steps:
-      - name: Extract version
-        id: extract-version
-        # Strip a string prefix from the git tag name:
-        run: |
-          echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
-
-      - uses: mislav/bump-homebrew-formula-action@v3
-        with:
-          formula-name: kubecolor
-          formula-path: Formula/k/kubecolor.rb
-          homebrew-tap: Homebrew/homebrew-core
-          base-branch: master
-          download-url: https://github.com/kubecolor/kubecolor/archive/refs/tags/${{ steps.extract-version.outputs.tag-name }}.tar.gz
-          commit-message: |
-            {{formulaName}} {{version}}
-
-            Created by https://github.com/mislav/bump-homebrew-formula-action
-        env:
-          COMMITTER_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
-
-  packaging:
-    name: Publish DEB & RPM packages
-    needs: goreleaser
-    runs-on: ubuntu-latest
-    environment: production
+    environment: ${{ inputs.environment }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -120,7 +117,8 @@ jobs:
           fetch-depth: 0
           ssh-key: ${{ secrets.PACKAGES_DEPLOY_KEY }}
 
-      - name: Set up GPG
+      - name: Set up GPG (only for production)
+        if: inputs.environment == 'production'
         env:
           PACKAGES_GPG_PUBKEY: ${{ secrets.PACKAGES_GPG_PUBKEY }}
           PACKAGES_GPG_KEY: ${{ secrets.PACKAGES_GPG_KEY }}
@@ -135,7 +133,8 @@ jobs:
           mkdir -pv dist
           mv -v artifacts/kubecolor_* dist/
 
-      - name: Sign RPMs
+      - name: Sign RPMs (only for production)
+        if: inputs.environment == 'production'
         run: assets/packaging/rpmsign-all.sh
 
       # Make sure to run rpmsign before doing attestations as rpmsign modifies the .rpm files
@@ -147,17 +146,29 @@ jobs:
       - name: Run createrepo-pkg.sh
         run: assets/packaging/createrepo-pkg.sh
 
+      - name: Sign RPM repomd.xml (only for production)
+        if: inputs.environment == 'production'
+        run: assets/packaging/rpm-repomd-sign.sh
+
+      - name: Disable deb signing (only when not production)
+        if: inputs.environment != 'production'
+        run: sed -i.bak '/^SignWith:/d' assets/packaging/distributions
+
       - name: Run reprepro-pkg.sh
         run: assets/packaging/reprepro-pkg.sh
 
       - name: Run version.sh
-        id: version
         run: assets/packaging/version.sh
+
+      - name: Upload assets to release
+        run: |
+          assets/packaging/gh-label-assets.sh dist/kubecolor_* \
+            | xargs gh release upload "${{ inputs.tag-name }}" --clobber --
 
       - name: Publish site
         env:
-          DO_PUBLISH: ${{ !contains(github.ref, '-') }}
-          VERSION: ${{ steps.version.outputs.version }}
+          DO_PUBLISH: ${{ !contains(inputs.tag-name, '-') && !inputs.dry-run }}
+          TAG_NAME: ${{ inputs.tag-name }}
           GIT_COMMITTER_NAME: kubecolor automation
           GIT_AUTHOR_NAME: kubecolor automation
           GIT_COMMITTER_EMAIL: noreply@github.com
@@ -165,10 +176,38 @@ jobs:
         working-directory: ./packages
         run: |
           git add .
-          git commit -m "Add rpm and deb packages for $VERSION"
+          git commit -m "Add rpm and deb packages for $TAG_NAME"
           if [ "$DO_PUBLISH" = "true" ]; then
             git push
           else
             git log --oneline @{upstream}..
             git diff --name-status @{upstream}..
           fi
+
+      - name: Publish release
+        if: "!inputs.dry-run"
+        run: |
+          gh release edit "${{ inputs.tag-name }}" --draft=false
+
+  homebrew:
+    name: Bump Homebrew formula
+    # Skip this job in case of git pushes to prerelease tags
+    if: "!contains(inputs.tag-name, '-')"
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+    needs: release
+    steps:
+      - uses: mislav/bump-homebrew-formula-action@v3
+        with:
+          formula-name: kubecolor
+          formula-path: Formula/k/kubecolor.rb
+          homebrew-tap: Homebrew/homebrew-core
+          base-branch: master
+          download-url: https://github.com/kubecolor/kubecolor/archive/refs/tags/${{ inputs.tag-name }}.tar.gz
+          commit-message: |
+            {{formulaName}} {{version}}
+
+            Created by https://github.com/mislav/bump-homebrew-formula-action
+        env:
+          COMMITTER_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
